Traceback (most recent call last):
  File "/home/sato-lab.org/takayu/project/sato-lab/GA/TEOptimize.py", line 93, in <module>
    main()
  File "/home/sato-lab.org/takayu/project/sato-lab/GA/TEOptimize.py", line 67, in main
    individual.fitness.values = toolbox.evaluate(individual)
  File "/home/sato-lab.org/takayu/project/sato-lab/GA/TEOptimize.py", line 37, in evaluate
    score = model.predict(seq)
  File "/home/sato-lab.org/takayu/project/sato-lab/GA/modules/TE_predictor.py", line 105, in predict
    toks = self.alphabet.encode(seq)
  File "/home/sato-lab.org/takayu/anaconda3/envs/GARNA/lib/python3.9/site-packages/esm/data.py", line 176, in encode
    return [self.tok_to_idx[tok] for tok in self.tokenize(text)]
  File "/home/sato-lab.org/takayu/anaconda3/envs/GARNA/lib/python3.9/site-packages/esm/data.py", line 176, in <listcomp>
    return [self.tok_to_idx[tok] for tok in self.tokenize(text)]
KeyError: 'UU'
